### ISSUE TITLE
Not really an issue, just wanted to say thanks

### ISSUE THREAD

**Issue by awulkan** [tochoromero/vuejs-smart-table#1]
Hey there. I just found this repo and I think you really created something great here! I'm planning on using it in a project right now. It fits my goals pretty well since it's easy to understand, while still being quite powerful, and it doesn't force you to override default css styling globally and so on.

If I find any problems I'll report them, good luck!

**Comment by tochoromero** [comment]
I'm glad you find it useful. This is something I have been using on my own projects for a while, and I thought it was time to open source it.
