### ISSUE TITLE
Clickable Icons in RC

### ISSUE THREAD

**Issue by Mashiane** [tochoromero/vuejs-smart-table#14]
Hi there

How can I add multiple icons on each row and then detect when each icon is clicked to find the corresponding row. For example Id like to have two columns, one with edit icon and another with delete icon. When edit / delete is clicked, these should fire different events but return the row id for example.

Thanks

**Comment by tochoromero** [comment]
You have complete control over the content of your cells, you just need to add as many icons as you need and use the `@click` handler for each of them to trigger the right actions.
