### ISSUE TITLE
Cannot know the sort order in the customSort function. Meaning one cannot group by in the list.

### ISSUE THREAD

**Issue by Bertram25** [tochoromero/vuejs-smart-table#17]
Hey,

Everything is the title.
Sometimes, you just want to be able to keep certain cases at the bottom or keep a sub filter in a certain order.

**Comment by tochoromero** [comment]
The custom sort function does receive the sort order as the 3rd parameter. You can see more details in the [documentation](http://localhost:8080/vuejs-smart-table/sorting/#custom-sort)
