### ISSUE TITLE
ERROR in ./node_modules/vuejs-smart-table/src/main.js

### ISSUE THREAD

**Issue by Fabszn** [tochoromero/vuejs-smart-table#18]
I Follow the installation guide. 
When I run my project I get the following error : 

`ERROR in ./node_modules/vuejs-smart-table/src/main.js
Module not found: Error: Can't resolve './SmartPagination' in '/Users/my/dev/projects/floxx/FloxxFrontApp/node_modules/vuejs-smart-table/src'
 @ ./node_modules/vuejs-smart-table/src/main.js 4:0-47 6:0-11:1 18:38-53
 @ ./src/app/index.js

ERROR in ./node_modules/vuejs-smart-table/src/main.js
Module not found: Error: Can't resolve './VTable' in '/Users/my/dev/projects/floxx/FloxxFrontApp/node_modules/vuejs-smart-table/src'
 @ ./node_modules/vuejs-smart-table/src/main.js 1:0-29 6:0-11:1 15:29-35
 @ ./src/app/index.js

ERROR in ./node_modules/vuejs-smart-table/src/main.js
Module not found: Error: Can't resolve './VTh' in '/Users/my/dev/projects/floxx/FloxxFrontApp/node_modules/vuejs-smart-table/src'
 @ ./node_modules/vuejs-smart-table/src/main.js 2:0-23 6:0-11:1 16:26-29
 @ ./src/app/index.js

ERROR in ./node_modules/vuejs-smart-table/src/main.js
Module not found: Error: Can't resolve './VTr' in '/Users/my/dev/projects/floxx/FloxxFrontApp/node_modules/vuejs-smart-table/src'
 @ ./node_modules/vuejs-smart-table/src/main.js 3:0-23 6:0-11:1 17:26-29
 @ ./src/app/index.js`

Any idea ? 

Many thanks

**Comment by derMart** [comment]
same here.
Adding the file extension .vue in all those errornous import statements inside ./node_modules/vuejs-smart-table/src/main.js the errors disappear. Maybe this should be considered as the fix.

**Comment by derMart** [comment]
as this maybe related to webpack which I am using: adding the extensions to be resolved automatically in the webpack config like this:
```
resolve: {
    extensions: ['.vue']
},
```
also resolves the issue. However the clean approach is to add those extensions in main.js IMHO.

**Comment by tochoromero** [comment]
Thank you for your help @derMart, I will add those extensions to the main.js to avoid this problem in the future
