### ISSUE TITLE
default sort icons unintuitive / reversed

### ISSUE THREAD

**Issue by derMart** [tochoromero/vuejs-smart-table#19]
Hi,

to me, it seems the default sort arrows should be reversed to be more intuitive. Consider the example from the docs: https://tochoromero.github.io/vuejs-smart-table/sorting/#table-header
![firefox_2DDi8SaU0R](https://user-images.githubusercontent.com/1069456/74521896-7a6e1480-4f1a-11ea-9177-347961cf17e6.png)

The arrow in Age is pointing upwards usually indicating ascending order, however the items are ordered descending. Hence I propose to switch up and down arrows.

**Comment by tochoromero** [comment]
Yes, the row icons are reversed, they need to be fixed.
