### ISSUE TITLE
Unexpected indentifier on first line of main.js 

### ISSUE THREAD

**Issue by patrickbolle** [tochoromero/vuejs-smart-table#2]
> { /home/patrick/Projects/wait-li/wait_li_app/node_modules/vuejs-smart-table/src/main.js:1
> (function (exports, require, module, __filename, __dirname) { import VTable from './VTable'
>                                                                      ^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at new Script (vm.js:79:7)
>     at createScript (vm.js:251:10)
>     at Object.runInThisContext (vm.js:303:10)
>     at Module._compile (internal/modules/cjs/loader.js:657:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at r (/home/patrick/Projects/wait-li/wait_li_app/node_modules/vue-server-renderer/build.js:8330:16)
>     at Object.<anonymous> (server-bundle.js:4270:18)
>     at __webpack_require__ (webpack:/webpack/bootstrap 405a98a1e209085803a4:25:0)
>     at Object.<anonymous> (plugins/pagination.js:1:0)
>     at __webpack_require__ (webpack:/webpack/bootstrap 405a98a1e209085803a4:25:0)
>     at Object.<anonymous> (.nuxt/index.js:1:0) statusCode: 500, name: 'SyntaxError' }

Using with Vue/Nuxt.JS

Was working fine earlier today, I must have restarted the server or something as now none of my pages load and bring up this error.

Any ideas here? Love the plugin, works exactly how I need!

Thanks so much.

**Comment by tochoromero** [comment]
I have never used Nuxt before, so I will not be of much help here. I will try to test it with Nuxt as soon I get a chance.

**Comment by gorankrajnc** [comment]
It is possible filtering  through two fields (name and surname)
Thanks you for answer

**Comment by tochoromero** [comment]
Yes, take a look at Custom Filters https://tochoromero.github.io/vuejs-smart-table/filtering/#custom-filters

**Comment by tochoromero** [comment]
@patrickbolle I got it to work with Nuxt, on top of having to register the plugin following https://nuxtjs.org/guide/plugins#vue-plugins I also had to make sure Nuxt would transpile the plugin, to do so in your `nuxt.config.js` you need to add the following to the `build` section:
```
build: {
    transpile: [/^vuejs-smart-table/]
  }
```
