### ISSUE TITLE
Error in getter for watcher "displayData": "TypeError: Cannot use 'in' operator to search for null

### ISSUE THREAD

**Issue by merigold** [tochoromero/vuejs-smart-table#3]
If sort column value is null, then sort function has this error:

Error in getter for watcher "displayData": "TypeError: Cannot use 'in' operator to search for 'full_name' in null"

**Comment by tochoromero** [comment]
Hello @merigold, can you please provide more details into how it is failing, if you could create a codepen or codesandbox it would be awesome. Thank you

**Comment by merigold** [comment]
If I have data like this:

```
model
{ name:'test',
cattegory:{
   name:'test-cattegory'
}
}
```

When cattegory is null, I have this error.

**Comment by tochoromero** [comment]
I'm not able to reproduce the issue. If the value for the sort column is `null` we just replace it with `''`
