### ISSUE TITLE
nuxt, Cannot read property '$scopedSlots' of undefined

### ISSUE THREAD

**Issue by leads** [tochoromero/vuejs-smart-table#30]
Hi. Trying to use this in a Nuxt project.

It works fine in local dev, but with `yarn build` and `yarn start` I get some errors:

<img width="592" alt="Screenshot 2020-09-04 at 21 23 02" src="https://user-images.githubusercontent.com/378237/92282077-d9b26700-eef4-11ea-82ab-feaced1de026.png">

I've included the plugin like this:
```
import Vue from 'vue'
import SmartTable from 'vuejs-smart-table'

Vue.use(SmartTable)

export default SmartTable
```

nuxt.config.js:
```
plugins: [
    {
      src: '~/plugins/smart-table.js',
      mode: 'client'
    }
  ],
```

Any ideas?

**Comment by tochoromero** [comment]
I will be completely honest, I don't use Nuxt personally and I have very little experience with it. I hope somebody with Nuxt experience is available to help.

**Comment by tochoromero** [comment]
I'm rewriting the library from the ground up, I will make sure the new version works with Nuxt. Please stay tuned for the new version release.
