### ISSUE TITLE
Sort order is unset after 3rd click

### ISSUE THREAD

**Issue by bryanbuchs** [tochoromero/vuejs-smart-table#36]
When clicking repeatedly on a `v-th` with a `sortKey`, the data is sorted ASC, then DESC, and then reverts to unsorted (array index order).  

In a way, that makes sense if you have *not* specified a `defaultSort`. If you have, I would expect the sort order to return to my default. 

(My personal preference would be that continued clicks on a sort header would continue to toggle between ASC/DESC for that column, but I can see the logic behind going ASC/DESC/UNSORT.)

**Comment by tochoromero** [comment]
It would be possible to add a property to control de behavior, I will work on it. Thanks for reporting it.

**Comment by richcoleman-alphatrust** [comment]
Oh man - I definitely prefer three states.  Most data tables have this.  Sad to see it was removed :(

Ideally, the sort icons would all be hidden and then they would just show the direction it's sorted on each click with a third state where they are hidden again.
