### ISSUE TITLE
Setting totalPages has no effect

### ISSUE THREAD

**Issue by 19peaches** [tochoromero/vuejs-smart-table#38]
I'm not sure if there's any reason to submit this, it seems that this is no longer being developed, 12 ignored pull requests and 13 ignored issues spanning back over a year.

When setting `totalPages` it doesn't make any difference the number I enter it always return 1 during render.

**Comment by tochoromero** [comment]
You are right, I haven't had the chance to maintain this project for a long time, but I'm back now.

I really don't understand the problem, `totalPages` should be a property to sync `VTable` with the `SmartPagination` component. How are you trying to use it, please reffer to the [documentation](http://localhost:8080/vuejs-smart-table/pagination/#total-pages-2) for an example.
