### ISSUE TITLE
CSS Customization for Pagination Failed

### ISSUE THREAD

**Issue by m-yahya** [tochoromero/vuejs-smart-table#4]
I'm trying to customize pagination:
`#app
  > div.app
  > div.send-tokens
  > div.track-tokens
  > div
  > div.transaction-table.box
  > div
  > nav
  > ul {
  background-color: #666769;
}

#app
  > div.app
  > div.send-tokens
  > div.track-tokens
  > div
  > div.transaction-table.box
  > div
  > nav
  > ul
  > li {
  background-color: #666769;
  list-style-type: none;
}`
The result is:
![image](https://user-images.githubusercontent.com/24489306/55639090-e8a95d00-57c8-11e9-83c2-343a83eea232.png)

Version info:
"vuejs-smart-table": "0.0.5"
"vue": "^2.6.6"

**Comment by tochoromero** [comment]
Hello, please refer to the Pagination CSS Customization Section to see how it is done:
https://tochoromero.github.io/vuejs-smart-table/pagination/#css-customization

**Comment by m-yahya** [comment]
I'm still having issues. I'm using CSS selectors (described in the example provided above) to customize the element but no luck. Here is an example:
/* this one is not working */
ul.pagination {
  background-color: aqua;
  list-style: none;
  display: flex;
}
/* this one is also not working */
.pagination {
  background-color: aqua;
  list-style: none;
  display: flex;
}
It would be great if you can provide a minimum example. Thanks
