### ISSUE TITLE
totalPagesChanged is triggered when a row is being deselected 

### ISSUE THREAD

**Issue by LexLextter** [tochoromero/vuejs-smart-table#46]
When I create a button for toggling selectAll a deselectAll there is a unexpecting behaviour. 

When all rows are selected and the user clicks on any row, the row is deleted, instead of deselected.

I noticed that totalPagesChanged event is triggred, however I don't understand why and how. 

This doesn't happened when user toggles them one by one. 

Thanks ;)

**Comment by tochoromero** [comment]
Thank you for reporting it.
I fixed the selectAll function. There will be a release shortly.
