### ISSUE TITLE
Support for VUE 3

### ISSUE THREAD

**Issue by MohabAbugabal** [tochoromero/vuejs-smart-table#48]
Hello everyone. I was wondering if there was a way around for Vue 3 support?

**Comment by tochoromero** [comment]
It is on the works. Today I was able to get it working. You can take a look in the `next` branch.
For the next version I'm keeping all the fundamentals the same but I'm changing all of the internals and some of the APIs to take advantage of the Composition API.

So there are a couple of big items left before I would consider using it on a production app:

- [ ] Rework the API to take advantage of the Composition API (breaking changes)
- [ ] Duplicate all the API for people still using the Object API
- [ ] Write the new documentation

Thank you for bearing with me, it makes me very happy to see people actually using the library :)

**Comment by tochoromero** [comment]
Duplicates #33
