### ISSUE TITLE
Support of downloading as CSV/XLSX

### ISSUE THREAD

**Issue by LexLextter** [tochoromero/vuejs-smart-table#52]
Hi, I wonder if there are any plans to add functionality to download the table as CSV or XLSX format?

Thanks!

**Comment by tochoromero** [comment]
Hello there.
I don't think I would want to add that functionality directly into the library. What I do need to add is a way to get all the data with all the transformations applied  as a plain JSON object, which then you will be able to manipulate whoever you need.

**Comment by LexLextter** [comment]
Thanks for the reply. Having a function to get JSON from the table would deffinitely help, thanks. Even though it might be a bit tricky since in our project we have some option, input and textarea elements inside the cells. ;)

**Comment by tochoromero** [comment]
@LexLextter for the `next` release you will have access to the data you need. You can take a look [here](https://vue-smart-table.netlify.app/table-state.html#rowsprepagination).

The `next` release should be ready pretty soon.

**Comment by LexLextter** [comment]
Amazing! Thank you very much!
