### ISSUE TITLE
Styling bug?

### ISSUE THREAD

**Issue by simonteoh** [tochoromero/vuejs-smart-table#55]
Hi, I had followed the steps of documentation but I had found that the styling is not working for this table. May I know what's the issue behind this?
![image](https://user-images.githubusercontent.com/66763712/114654602-1f51d080-9d1d-11eb-9a02-ebce90e88ff9.png)

**Comment by tochoromero** [comment]
Hello there.
The documentation is using bootstrap to style the table.
Smart Table doesn't include any styling, that is on purpose, we don't want to make any assumptions on how it should look like, it is up to you to do so.
I would recommend using bootstrap to get some quick styles going.
