### ISSUE TITLE
Have an event emitted when someone clicks on a column header

### ISSUE THREAD

**Issue by Bertram25** [tochoromero/vuejs-smart-table#57]
Hey there,

While working with vue smart table in the context of adding infinite scrolling support to on of our list, we encountered the fact that we need to reset the list size whenever the user clicks on a column header.

To do so, we'd need to know when this happened and we'd miss an emitted event whenever the sort() method is called.
E.g: here: https://github.com/tochoromero/vuejs-smart-table/blob/master/src/VTh.vue#L93

So here is my humble request to see this added. Happy to get your own thoughts about this one also.

Cheers,

**Comment by tochoromero** [comment]
This is a very good idea, I will implement it.

**Comment by tochoromero** [comment]
This was added to the `next` version.
The `next` release should be ready pretty soon.
You can get a preview at https://vue-smart-table.netlify.app/

**Comment by Bertram25** [comment]
@tochoromero Thanks! Just witnessed that there: https://github.com/tochoromero/vuejs-smart-table/blob/next/src/VTh.ts#L114
