### ISSUE TITLE
Double initialization of VueJS

### ISSUE THREAD

**Issue by DevLazio** [tochoromero/vuejs-smart-table#65]
Hi,
I noticed a problem when using your library (nice job there btw), where VueJS would be loaded twice after upgrading to Laravel-Mix 6. 
![image](https://user-images.githubusercontent.com/2280811/122364962-8f1d4b00-cf5a-11eb-8944-a710740a18bc.png)

After a bit of testing I found out that moving the vue dependencie to devDependencies or using the same version as the one I'm using fixed it without any impact.
```
"dependencies": {
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.6.3",
    "@vue/cli-plugin-babel": "^3.1.1",
    "@vue/cli-plugin-eslint": "^3.1.5",
    "@vue/cli-plugin-unit-mocha": "^3.1.1",
    "@vue/cli-service": "^3.1.4",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-eslint": "^10.0.1",
    "bootstrap": "^4.2.1",
    "chai": "^4.1.2",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0-0",
    "lint-staged": "^7.2.2",
    "mocha-junit-reporter": "^1.18.0",
    "sass": "^1.30.0",
    "sass-loader": "^10.1.0",
    "vue": "^2.5.17",
    "vue-template-compiler": "^2.5.17",
    "vuepress": "^0.14.8"
  },```

Should I send a pull request with these changes ?

**Comment by tochoromero** [comment]
Thank you for reporting this.
All of this should be fixed in the `next` version, which works for both Vue 2 and Vue 3.
