### ISSUE TITLE
SSR support?

### ISSUE THREAD

**Issue by msurguy** [tochoromero/vuejs-smart-table#7]
Hi! Thanks for this package! 
I'd like to ask about SSR support as I cannot get this package to work within Nuxt.js SSR context. 

Do you have any idea on how to make that work?

**Comment by tochoromero** [comment]
It should work with Nuxt, but there is some configuration you need to do for any vue plugin to work with Vuex, here is a comment with details.

https://github.com/tochoromero/vuejs-smart-table/issues/2#issuecomment-480504795
