### ISSUE TITLE
Row selection API

### ISSUE THREAD

**Issue by etune** [tochoromero/vuejs-smart-table#8]
I'm adding some of my own things to the multi-select feature that's built into the table.  I've found myself in a situation where I'm referencing the `VTable`component and accessing some methods that way.

https://github.com/tochoromero/vuejs-smart-table/blob/08c381836499dd0a08817b947be942d9d32becd4/src/VTable.vue#L201-L220

I know this is a dangerous thing to do but I couldn't find another way. 

Any chance there could be a "more public" API for these methods?

Thanks. I really like this component.

**Comment by tochoromero** [comment]
Hello there.
I created those methods in the `VTable` component with the intention of being used with `ref`.
I cannot think of a better way to expose those methods. If you have any ideas please tell.

**Comment by etune** [comment]
I can't think of a better way. I feel better knowing that you intended for people to do what I'm doing. I'm not as worried about breaking changes being introduced.

Thanks so much for everything.
