### ISSUE TITLE
ReferenceError: displayData is not defined when trying out basic example

### ISSUE THREAD

**Issue by LaundroMat** [tochoromero/vuejs-smart-table#9]
When trying this code

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue-smart-table/2.5.0/vue-smart-table.min.js" defer></script>
</head>
<body>
 <div id="app" class="container">
    <v-table :data="users">
        <thead slot="head">
            <th>Name</th>
        </thead>
        <tbody slot="body" slot-scope="{displayData}">
          <tr v-for="row in displayData" :key="row.id">
                {{displayData}}
            </tr>
        </tbody>
    </v-table>
</div>
</body>
<script>
window.addEventListener('load', function () {
    Vue.config.devtools = true;

    var app = new Vue({
        el: '#app',
        data: function() {
            return {
                users: [
                  {name:"you"}, {name: 'me'}
                ]
            }
        }
    });
})
</script>
</html>

```

I'm getting a

    ReferenceError: displayData is not defined

error. 

I'm pretty new to VueJS, but I can't find a way of making this work unfortunately.

(Also, [according to the docs](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax), the `slot` and `slot-scope` directives are deprecated, but that's got nothing to do with my issue).

[JSBin](https://jsbin.com/zukoposibe/edit?html,js,console,output)

**Comment by tochoromero** [comment]
The CDN you are using for the library is wrong, in fact, I haven't created a CDN for it. I recommend using https://codesandbox.io/embed/vue and there you can just add any npm dependency.

**Comment by LaundroMat** [comment]
Thanks -- I've never encountered such an issue before. Keep up the good work!
